[tool.poetry]
name = "todojango"
version = "0.1.0"
description = ""
authors = ["lomalo890 <george2066@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.1.2"
django-allauth = "^65.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
